**Amrit Dhillon**
**GSB545 Homework #2 Bagging and Boosting Main Notebook**

**#1 - #3 [DONE]**

------------------------------------------------------------------------------------------------------------------------------------------------------------

**#4** Find and upvote 3-4 notebooks or discussion posts that you find particularly insightful or you could realistically apply in your own modeling. Provide the URLs in your Homework document. Posting on discussion boards in Kaggle is a great way to get some exposure, but is not required.

------------------------------------------------------------------------------------------------------------------------------------------------------------

**URL 1:** https://www.kaggle.com/code/tsunamazda/predicting-irrigation-need-baseline-xgboost

**Reasoning for Choice:**

- Provides easy to understand XGBoost baseline model and uses balanced accuracy (evaluation metric)

- Shows the impact of key hyperparameters like learning_rate, max_depth, and n_estimators, which control how quickly the model learns and how complex each tree is

- Contained ideas like feature importances and class weighting that I could apply to improve my models

- Provides a clear baseline for how XGBoost performs without heavy tuning to compare against tuned model improvements later


**URL 2:** https://www.kaggle.com/code/simarbirsinghsandhu/xgboost-optuna-gpu-cv-0-972

**Reasoning for Choice:**

- Shows a more optimized version of the XGBoost model with Stratified K-Fold cross validation and using Optuna for tuning which we just learned about

- Helped understand how tuning learning rate, depth, and subsampling could impact performance

- Shows how subsampling and regularization parameters help prevent overfitting in XGBoost by adding randomness and controlling model complexity

- Highlights how boosting models like XGBoost can achieve strong performance without extensive feature engineering, relying on iterative error correction instead


**URL 3:** https://www.kaggle.com/code/goggle3462/predicting-irrigation-need

**Reasoning for Choice:**

- Gives clear approach for Random Forest Classifier bagging model using a simple train/test split baseline

- Useful to understand basic Random Forest hyperparameters like number of trees, depth, etc.

- Showed clear way to handle categorical variables using encoding


**URL 4:** https://www.kaggle.com/code/xjoannax88/ps-s6e4-irrigation-need-prediction

**Reasoning for Choice:**

- Included full preprocessing, encoding, and transformation pipeline in addition to cross validation for RandomForest 

- Demonstrates how Random Forest reduces variance by averaging many decision trees, which helped reinforce why it is a good baseline bagging model

- Shows the impact of key hyperparameters like n_estimators and max_depth, which control model complexity and performance, giving me a starting point for tuning my own model
    
- Uses feature subsampling within trees, which is a core idea in Random Forest that helps reduce overfitting
------------------------------------------------------------------------------------------------------------------------------------------------------------

**#5** Create an EDA notebook for the competition. Do your initial EDA in that notebook and provide the URL in your Homework document.

EDA Notebook URL: https://github.com/bigturtle13/GSB545/blob/main/Kaggle%20Playground%20Series%20Competition/Kaggle%20Homework%5BEDA%5D%20-%20Amrit%20Dhillon%20-%20therealbigturtle13.ipynb


SweetViz EDA Report URL: https://github.com/bigturtle13/GSB545/blob/main/Kaggle%20Playground%20Series%20Competition/sweetviz_comparison_report.html

------------------------------------------------------------------------------------------------------------------------------------------------------------


**#6** Use two distinct modeling approaches, one bagging and one boosting. You may build other models, but the goal for the homework is to compare bagging and boosting approaches. You must submit at least one boosting and one bagging set of predictions to Kaggle (gets your submission workflow established). Consider exploring models we didn't cover in class. Make sure you are using cross-validation or another validation metric to improve your modeling. Do some tuning but don't spend hours and hours on it at this stage. Again, consider posting a public notebook on Kaggle (many people post only one or two notebooks out of many that they create).

Bagging Notebook URL: https://github.com/bigturtle13/GSB545/blob/main/Kaggle%20Playground%20Series%20Competition/Kaggle%20Homework%5BBagging%5D%20-%20Amrit%20Dhillon%20-%20therealbigturtle13.ipynb

Boosting Notebook URL: https://github.com/bigturtle13/GSB545/blob/main/Kaggle%20Playground%20Series%20Competition/Kaggle%20Homework%5BBoosting%5D%20-%20Amrit%20Dhillon%20-%20therealbigturtle13.ipynb

------------------------------------------------------------------------------------------------------------------------------------------------------------

**#7.** In your Kaggle Homework document provide:

- URLs for the resources you upvoted on the competition site.  Discuss why you chose each--how will it help you improve your approach? [**PROVIDED ABOVE**]

- Links to your EDA notebook and bagging and boosting notebook(s). [**PROVIDED ABOVE**]

- Discuss your modeling approaches. What did you try? What worked well? What didn't work well? Were model improvements meaningful or small? Make sure to use performance metrics in your discussion. Also provide leaderboard scores for the models. A table might be useful for organizing the metrics and leaderboard scores. [**PROVIDED BELOW**]

- How did boosting versus bagging compare for your work? [**PROVIDED BELOW**]

Discuss your modeling approaches. What did you try? What worked well? What didn't work well? Were model improvements meaningful or small? Make sure to use performance metrics in your discussion. Also provide leaderboard scores for the models. A table might be useful for organizing the metrics and leaderboard scores.

- I tested two main ensemble approaches: Random Forest (bagging) and XGBoost (boosting), both evaluated using stratified CV with balanced accuracy due to class imbalance

- The XGBoost model performed best, achieving a *CV score of 0.9694* and a *Kaggle leaderboard score of 0.9683* after hyperparameter tuning and some feature engineering inspired by notebooks that I looked through

- The Random Forest model also performed well, with a *CV score of 0.9631* and a *Kaggle leaderboard score of 0.9606*, but it was consistently slightly worse than XGBoost

- In my opinion, because it was so difficult to get model imrovements, the performance improvement from Random Forest to XGBoost (~0.007–0.008) was meaningful, showing that boosting provided better predictive power than bagging for this dataset

- The gains from feature engineering were minimal but present, and so I kept them within my models

- Using RandomizedSearchCV instead of full GridSearchCV helped reduce runtime significantly(it was taking forever before I used it) while still finding strong hyperparameters

- One approach that did not go well was CatBoost, which caused repeated issues (library errors, file writing issues, and long runtimes). Because of this, I was unable to efficiently tune or evaluate it, so I focused on XGBoost instead. At some point I want to try it out again

In [1]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["XGBoost", "Random Forest"],
    "Type": ["Boosting", "Bagging"],
    "Stratified K-Fold CV Score": [0.9694, 0.9631],
    "Kaggle Score": [0.9683, 0.9606]
})

results

,Model,Type,Stratified K-Fold CV Score,Kaggle Score
0,XGBoost,Boosting,0.9694,0.9683
1,Random Forest,Bagging,0.9631,0.9606


How did boosting versus bagging compare for your work?

- In my notebooks, the boosting model (XGBoost) consistently outperformed the bagging model (Random Forest) in both cross-validation and Kaggle leaderboard performance in different iterations of both models

- XGBoost achieved a *CV score of 0.9694* and a *Kaggle leaderboard score of 0.9683*, while Random Forest achieved a *CV score of 0.9631* and a *Kaggle leaderboard score of 0.9606*

- The performance difference (~0.007–0.008) was meaningful but not drastic, indicating that both models were strong, but boosting provided a clear advantage

- The improved performance of XGBoost is likely because of its ability to build trees sequentially and correct previous errors it made, whereas Random Forest builds trees independently and focuses on reducing variance

- Overall, boosting proved to be more effective for this dataset, but the bagging model, Random Forest, still served as a strong and reliable baseline

------------------------------------------------------------------------------------------------------------------------------------------------------------

**#8.** What is your "phase 2" plan to improve your model performance? Note that although the leaderboard is fun to watch, you are not graded on it (and a shake up often occurs at the end!)

- In "phase 2", now that I have established strong baselines for each of my bagging and boosting models, I would like to tune more hyperparameters like colsample_bytree, min_child_weight, and gamma to see if improvements can still be made

- I would also like to further experiment with feature engineering, as it allowed me to make incremental improvements on my models. One type of engineered features I'd like to use specifically include interactions between weather variables like temperature and humidity or rainfall and soil moisture

- Furthermore, although I experienced difficulty with other models like CatBoost this time around I would like to attempt using models like it again. I would like to see how CatBoost as well as LightGBM fare against XGBoost.

- Apart from this I'm sure there are many improvements and iterations of my models to come. As I learn more things in class I will apply these concepts to my models, as well as anything I can find online.